# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12lrrwhxNeya5Ui0cnJtjdbLpq-3yoEkA
"""

!pip install paddlepaddle
!pip install paddleocr
!pip install paddlepaddle-gpu

import paddleocr
from paddleocr import PaddleOCR

ocr = PaddleOCR()

# Replace 'your_image_path.jpg' with the actual path to your image
result = ocr.ocr('/content/IMG-20230708-WA0040.jpg')

words = []
for line in result:
    for word_info in line:
        words.append(word_info[1][0])
print(words)

