# -*- coding: utf-8 -*-
"""use_me_ocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171OAOFL4r06F5iZFLi1XX8GkY9QGQc_2
"""

!sudo apt install tesseract-ocr
!pip install pytesseract

import pytesseract
import shutil
import os
import random
import numpy as np
try:
 from PIL import Image
except ImportError:
 import Image

image_path_in_colab='/content/img.jpg'
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)

# spark-ocr, craft, digit detection paddle, mm, doctr-ocr

img = Image.open(image_path_in_colab)
img

image_path_in_colab='/content/img2.jpg'
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)
img = Image.open(image_path_in_colab)
img

